cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'openssl'
brew 'openshift-cli'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'atom'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'skype'
cask 'steam'
cask 'vlc'
